# Generated by Django 4.0.5 on 2022-06-10 13:57

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='TaskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_volunteer_level', models.IntegerField(verbose_name='Минимальный уровень волонтёра')),
                ('min_volunteer_rating', models.IntegerField(verbose_name='Минимальный рейтинг волонтёра')),
            ],
            options={
                'verbose_name': 'Настройка для задачи',
                'verbose_name_plural': 'Настройки для задачи',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Не более 50 символов', max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('datetime', models.DateTimeField(verbose_name='Время и дата')),
                ('max_volunteer', models.IntegerField(blank=True, verbose_name='Количество волонтёров')),
                ('point_on_map', models.CharField(max_length=60, verbose_name='Метка на карте')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
