# Generated by Django 4.0.5 on 2022-06-10 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.employer', verbose_name='Работодатель'),
        ),
        migrations.AddField(
            model_name='task',
            name='photos',
            field=models.ManyToManyField(to='tasks.photo', verbose_name='Фотографии'),
        ),
        migrations.AddField(
            model_name='task',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tasksettings', verbose_name='Настройка для задачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='volunteers',
            field=models.ManyToManyField(related_name='task', to='user.volunteer', verbose_name='Волонтёры'),
        ),
    ]
