# Generated by Django 4.0.5 on 2022-06-11 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_photos_alter_task_volunteers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='max_volunteer',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество волонтёров'),
        ),
    ]
