# Generated by Django 4.0.5 on 2022-06-11 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_username'),
        ('tasks', '0004_alter_task_max_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_tasks', to='user.employer', verbose_name='Работодатель'),
        ),
    ]
