# Generated by Django 4.0.5 on 2022-06-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
