# Generated by Django 4.0.5 on 2022-06-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.PositiveIntegerField(null=True, verbose_name='ID Телеграм Чата'),
        ),
    ]
