# Generated by Django 4.0.5 on 2022-06-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(help_text='без @', max_length=50, unique=True, verbose_name='Username Телеграма (без @)'),
        ),
    ]
